// Self-hosted github-readme-stats instance. The shared public instance
// (github-readme-stats.vercel.app) is rate-limited and periodically paused.
const GRS = 'https://github-readme-stats-plum-psi.vercel.app';

// Upstream card sources. Kept in sync with scripts/fetch-stats.mjs, which
// caches them into public/stats so the site does not depend on these services
// at runtime.
export const githubStats = {
  activity: `${GRS}/api?username=ehgp&include_all_commits=true&show_icons=true&theme=github_dark&hide_border=true`,
  streak: 'https://github-readme-streak-stats.herokuapp.com/?user=ehgp&theme=tokyonight&hide_border=true',
  topLanguages: `${GRS}/api/top-langs/?username=ehgp&theme=github_dark&hide_border=true&hide=Jupyter%20Notebook,css,html,scss,solidity,python,MATLAB&layout=compact`
};

// Locally cached copies generated by scripts/fetch-stats.mjs. Served from the
// static export, so these render even when the upstream services are down.
// `wakatime` is built from the WakaTime JSON API and rendered to SVG by the
// fetch script (no github-readme-stats middleman; see scripts/fetch-stats.mjs).
export const localStats = {
  activity: '/stats/activity.svg',
  streak: '/stats/streak.svg',
  topLanguages: '/stats/top-langs.svg',
  wakatime: '/stats/wakatime.svg'
};

export const driveEmbeds = {
  projects: 'https://drive.google.com/file/d/1UvN-gFCw8ms_Yo7RnwL3kBEOU8pJAKRE/preview',
  resumeTech: 'https://drive.google.com/file/d/1yokQ2vI0eXsm9Uc5RfBffDwV5nTR01wz/preview'
};
