// Locally cached cards generated by scripts/fetch-stats.mjs and served from
// the static export, so the site has no runtime dependency on external stats
// services. `activity` and `topLanguages` are rendered from the GitHub API,
// `wakatime` from the WakaTime API; `streak` is cached from
// github-readme-streak-stats.herokuapp.com with the committed copy as
// fallback.
export const localStats = {
  activity: '/stats/activity.svg',
  streak: '/stats/streak.svg',
  topLanguages: '/stats/top-langs.svg',
  wakatime: '/stats/wakatime.svg'
};

export const driveEmbeds = {
  projects: 'https://drive.google.com/file/d/1UvN-gFCw8ms_Yo7RnwL3kBEOU8pJAKRE/preview',
  resumeTech: 'https://drive.google.com/file/d/1yokQ2vI0eXsm9Uc5RfBffDwV5nTR01wz/preview'
};
