# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: python-lint-test-pages

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8==3.9.0
          python -m pip install black==21.12b0
          python -m pip install pydocstyle==6.0.0
          pip install pipenv
          python -m pip install -U pip

      - name: flake8
        run:
          python -m flake8 . --ignore=E203,E266,E501,W503,F403,F401 --max-complexity=18 --max-line-length=88 --select=B,C,E,F,W,T4,B9

      - name: black
        run:
          python -m black . --check --verbose

      - name: pydocstyle
        run:
          python -m pydocstyle . --convention=google

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: unit test
        run: |
          echo 'No Unit Test Found'

  pages:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'

      # You can test your matrix by printing the current Python version
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Flask Build
      run: |
        pip install -r requirements.txt
        python freezer.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: html-docs
        path: _build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build
